kind: stack
description: Stack of OBS Studio non-Qt dependencies without building tools

depends:
- components/amf-headers.bst
- components/asio.bst
- components/extra-cmake-modules.bst
- components/ffmpeg.bst
- components/jansson.bst
- components/libajantv2.bst
- components/libdatachannel.bst
- components/libfdk-aac-stripped.bst
- components/libqrcodegencpp.bst
- components/librist.bst
- components/luajit.bst
- components/mbedtls.bst
- components/nlohmann-json.bst
- components/nv-codec-headers.bst
- components/rnnoise.bst
- components/simde.bst
- components/srt.bst
- components/uthash.bst
- components/websocketpp.bst
- components/x264.bst
- components/qsv-maybe.bst
